version: "3"

services:
  api:
    image: 'node:14.17.1'
    container_name: inventory_backend
    restart: always
    networks:
      - inventory_control_networks
    ports:
      - 3001:3001
    volumes:
      - ../api:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "yarn && yarn dev"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  frontend:
    image:  'node:14.17.1'
    container_name: inventory_control_front
    restart: always
    networks:
      - inventory_control_networks
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes: # Volume binding
      - ../inventory_control:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "yarn && yarn start"
  database:
    image: 'mongo:4.2'
    container_name: 'database'
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongo-volume:/data/db
    networks:
      - inventory_control_networks
    ports:
      - '27017:27017'

networks:
  inventory_control_networks:
    driver: bridge