version: '3'

services:
  api:
    image: node:latest
    container_name: api_inventory
    restart: always
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - inventory_control
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ../../backend:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"